### PR TITLE
Wayland support

### PR DESCRIPTION
**Pull request by ripe-mangos**
Fix for Wayland support and eframe version bump

### CODE REVIEW

**Comment by sshiroi** [comment]
Thanks,
isn't this eframe version downgrade?
If newest version doesn't work with wayland its ok.
If we add Cargo.lock to gitignore i think we should also delete it first. I do eventually want  a commited Cargo.lock again because it makes packaging for nixos easyer but that isn't important now.

**Comment by sshiroi** [comment]
feature wgpu does not build on my machine. With some error relating to windows in wgpu-hal dxgi...
I have confirmed that current master doesn't work for me in sway either.

But by removing 
https://github.com/sshiroi/vmux/blob/10c24894a3ffc86da4b0301640bda532a16ac6e3/vmux_gui/src/main.rs#L23
it does, but under xwayland.

I'm also interested why you changed to opt-levels?
I don't remember why I changed them for vmux-lib anymore but I think it was that I was doing memcpy via forloops and that was very slow on dev by default.

On another note. I saw that you have a rust ass-library. Do you think It could be useful for spliting subtiles for matroska like described here in ```SSA/ASS Subtitles```.
https://www.matroska.org/technical/subtitles.html

**Comment by ripe-mangos** [comment]
I also had some issues with wgpu-hal and dxgi.
I'm assuming you're running all of this on NixOS w/ sway? I tested on Hyprland and don't have Xwayland installed, so I think this should work: add the `resolver = "2"` line in your workspace ([like this](https://github.com/ripe-mangos/vmux/blob/b280fac32821f8482d267dbb3593f342521e45b9/Cargo.toml#L2)). [This issue](https://github.com/gfx-rs/wgpu/issues/2356) has some more info.
I honestly have no idea why eframe got downgraded; I just ran `cargo update` and that's what it did. You should be fine to use 0.21.3.

I kinda gave up on my ASS library, but yeah, I think it would work for this use case. It would be easier than libass at least.
Only issue: there isn't *really* a standard (whatever libass does goes), though the basic structure isn't played with too much. Really just a non-issue I wanted to vent about :'D

Lastly, I changed the opt-levels to optimize dependencies in dev. The reasoning for this is described [here](https://bevyengine.org/learn/book/getting-started/#compile-with-performance-optimizations) (can't find an egui link).
And I didn't add it, but for the release profile you probably want this:
```toml
[profile.release]
opt-level = 3
lto = true
```

**Comment by sshiroi** [comment]
> I'm assuming you're running all of this on NixOS w/ sway?

Yes, I mostly use plasma on X though.

Check if everything works for you with https://github.com/sshiroi/vmux/commit/a5a00f07e60d3c98d78d84ea3e5cc03022c5ee9b
 
It still gets picked up by xprop in sway for me, but don't know if thats relevant.

**Comment by ripe-mangos** [comment]
Yeah, `a5a00f0` works for me.

**Pull request closed without merging**
